# $Copyright: Copyright (c) 2024 Veritas Technologies LLC. All rights reserved $

# Verify whether the NetBackup client has the NetBackup server software installed
# The install will not be performed if the client is a NetBackup server
- name: "NBU-CLIENT-{{ nbu_playbook_type|upper }} -> Verify whether NetBackup server software is currently installed"
  ansible.builtin.shell: ( rpm -qa | grep "{{ nbu_server_rpm_name }}" )
  changed_when: false
  register: nbu_server_rpm_check
  failed_when: false

# Verify whether the NetBackup client has the NetBackup client software installed
# Fail if bptm or version files exist - Server is NetBackup
- name: "NBU-CLIENT-{{ nbu_playbook_type|upper }} -> Verify the bptm and version files exist on NetBackup client"
  ansible.builtin.stat:
    path: "{{ netbackup_file }}"
  register: netbackup_files
  with_items:
    - /usr/openv/netbackup/bin/bptm
    - /usr/openv/netbackup/version
  loop_control:
    loop_var: netbackup_file
  failed_when: false

- name: Ansible::Log.info
  fail:
    msg:  This machine is a NetBackup Primary or Media Server, therefore exit immediately. Installing this Playbook on a Primary or Media Server would cause a significant outage.
  when: netbackup_files.results[0].stat.exists or netbackup_files.results[1].stat.exists or nbu_server_rpm_check.rc == 0

# EOF