# $Copyright: Copyright (c) 2024 Veritas Technologies LLC. All rights reserved $

- name: "NBCHECK -> Removing existing VRTSnbpck package and /usr folder from {{ os_path_openv_tmp  }}"
  file:
    path: "{{ item }}"
    state: absent
  with_items:
   - "{{ os_path_openv_tmp  }}/VRTSnbpck.rpm"
   - "{{ os_path_openv_tmp  }}/usr"

- name: "NBCHECK -> Create [{{ os_path_openv_tmp }}] directory if it does not exist"
  ansible.builtin.file:
    path: "{{ os_path_openv_tmp }}"
    state: directory

- name: "NBCHECK -> Download VRTSnbpck rpm package to {{ os_path_openv_tmp  }}"
  get_url:
    url: "{{ nbu_artifactory_repo_base_url }}{{ artifactory_repo }}{{ nbu_path_repo_base_pkg }}/VRTSnbpck.rpm"
    dest: "{{ os_path_openv_tmp  }}/VRTSnbpck.rpm"
  register: download_status_register
 
- name: "NBCHECK -> Check VRTSnbpck.rpm package existence in {{ os_path_openv_tmp  }}"
  stat:
    path: "{{ os_path_openv_tmp  }}/VRTSnbpck.rpm"
  no_log: true
  register: file_status_register

- name: "NBCHECK -> Extracting nbcheck file from VRTSnbpck.rpm"
  ansible.builtin.shell: ( rpm2cpio VRTSnbpck.rpm | cpio -idmv)
  args:
    chdir: "{{ os_path_openv_tmp  }}"
  register: extract_file_status_register
  no_log: true
  when: file_status_register.stat.exists

- name: "NBCHECK -> Set-Fact NBCheck test name list based on nbu role"
  set_fact:
    test_name_list: "{{ nbcheck_test_name[nbu_role] }}"

