# $Copyright: Copyright (c) 2024 Veritas Technologies LLC. All rights reserved $

# NetBackup Client - REMOVE - CLIENT
- name: NETBACKUP -> CLIENT REMOVE ("RedHat")
  gather_facts: false
  become: yes
  hosts: all

  pre_tasks:
    - name: Retrieving host distribution
      setup:
        gather_subset:
          - "!all"
          - "!min"
          - "distribution"
    - name: "NBU-CLIENT-{{ nbu_playbook_type|upper }} -> Load configurable variables"
      ansible.builtin.include_vars: "vars/main.yml"
      tags: ["always"]
      no_log: True

  roles:
    - role: 'netbackup/redhat'            # Load netbackup default vars
    - role: 'generic/os_compatibility'
    - role: 'generic/server_check'        # Make sure that the execution isn't running on a NetBackup Server
    - role: 'generic/nbu_version_check'
    - role: 'netbackup/redhat/nbu-client-remove/v1.0'
  vars:
    nbu_playbook_type: "remove"

# EOF