# $Copyright: Copyright (c) 2025 Veritas Technologies LLC. All rights reserved $

# NetBackup Server - Upgrade - CLIENT
- name: NETBACKUP -> CLIENT UPGRADE ("Linux")
  gather_facts: true
  become: yes
  hosts: all
  environment:
    NB_TMPDIR: "/usr/openv/tmp"
    PAR_GLOBAL_TMPDIR: "/usr/openv/tmp"
  pre_tasks:
    - name: Retrieving host distribution
      setup:
        gather_subset:
          - "!all"
          - "!min"
          - "distribution"
    - name: "NBU-{{ nbu_role|upper }}-{{ nbu_playbook_type|upper }} -> Load configurable variables"
      ansible.builtin.include_vars: "vars/linux.yml"
      tags: ["always"]
      no_log: True

  roles:
    - role: 'netbackup/linux'                                   # Load netbackup default vars
    - role: 'generic/os_compatibility'
    - role: 'generic/is_nbu_version_supported'
    - role: 'helper/detect_partial_install'
    - role: 'generic/nbu_compatibility'
    - role: 'generic/nbu_verification'
    - role: 'netbackup/linux/nbu-client-install/v2.0'
    - role: 'generic/nbu_verification'                          # Verifies certificate specific checks and report
    - role: 'netbackup/linux/nbu-install-eeb/v2.0'
  vars:
    nbu_role: "client"
    nbu_playbook_type: "upgrade"

# EOF