# $Copyright: Copyright (c) 2025 Veritas Technologies LLC. All rights reserved $

# NetBackup Certificate Deployment - LINUX
- name: NETBACKUP -> CERTIFICATE DEPLOYMENT ("Linux")
  gather_facts: true
  become: yes
  hosts: all
  pre_tasks:
    - name: Retrieving host distribution
      setup:
        gather_subset:
          - "!all"
          - "!min"
          - "distribution"
    - name: "NBU-CERTIFICATE-DEPLOYMENT -> Load configurable variables"
      ansible.builtin.include_vars: "vars/linux.yml"
      tags: ["always"]
      no_log: True
  roles:
    - role: 'netbackup/linux'                   # Load netbackup default vars
    - role: 'generic/is_nbu_version_supported'
    - role: 'generic/nbu_compatibility'
    - role: 'netbackup/common/nbu-get-certificate/v2.0'
  vars:
    nbu_playbook_type: "certificate"  

# EOF