# $Copyright: Copyright (c) 2024 Veritas Technologies LLC. All rights reserved $

# NetBackup Server - Install - Media Server
- name: NETBACKUP -> MEDIA SERVER INSTALL
  gather_facts: true
  become: yes
  hosts: all
  pre_tasks:
    - name: Retrieving host distribution
      setup:
        gather_subset:
          - "!all"
          - "!min"
          - "distribution"
    - name: "NBU-{{ nbu_role|upper }}-{{ nbu_playbook_type|upper }} -> Load configurable variables"
      ansible.builtin.include_vars: "vars/linux.yml"
      tags: ["always"]
      no_log: True
  roles:
   - role: 'netbackup/linux'                                    # Load netbackup default vars
   - role: 'generic/os_compatibility'
   - role: 'generic/is_nbu_version_supported'
   - role: 'generic/nbu_compatibility'
   - role: 'netbackup/linux/pre-install-os-task/v1.1'           # Perform pre-upgrade tasks - OS related
   - role: 'netbackup/linux/nbu-media-install/v1.1'
   - role: 'netbackup/common/nbu-get-certificate/v1.1'
   - role: 'generic/nbu_verification'                           # Verifies certificate specific checks and report 
   - role: 'netbackup/linux/nbu-install-eeb/v1.1'

  vars:
    # Role Control
    nbu_role: "media"
    nbu_playbook_type: "install"

  #EOF
