# $Copyright: Copyright (c) 2024 Veritas Technologies LLC. All rights reserved $

# Install NetBackup EEBS for the specific NetBackup Version 
- name: NBU-EEB-INSTALL -> Include tasks for NetBackup EEB installation 
  ansible.builtin.include_tasks: t01_base_patch_eeb.yml
  loop: "{{ nbu_eeb_ordered.client[nbu_version] }}"
  when:
   - nbu_eeb_ordered.client[nbu_version] is defined

# EOF