# $Copyright: Copyright (c) 2024 Veritas Technologies LLC. All rights reserved $

##############################################################################
####  Generic tasks to verify OS specification                            ####
####  - OS version compatibility against provided production version      ####
####  - Check existence of OS native dependent packages and install if    ####
####    found missing                                                     ####
##############################################################################

# Verify the OS distribution major release for SLES
# Expected result is SLES versions 12 or 15
- name: "NBU-OS-COMPATIBILITY -> Verify the OS distribution major version is compatible with NetBackup Version"
  ansible.builtin.assert:  
    that: (ansible_distribution_major_version  == '12') or (ansible_distribution_major_version  == '15')
    success_msg: "PASS - Operating system distribution major version is compatible - OS distribution major version: {{ ansible_distribution_major_version }}"
    fail_msg: "ERROR - Incompatible OS Distribution Major version - Detected OS Distribution Major Version is {{ ansible_distribution_major_version }}"
    quiet: true

# EOF
