# $Copyright: Copyright (c) 2025 Veritas Technologies LLC. All rights reserved $
#
# ##################################################################
# #### Install packages for recovery server - ("Linux/Windows") ####
# ##################################################################

- name: "INSTALL-PACKAGES -> Install packages for recovery server."
  ansible.builtin.include_tasks: "{{ ansible_system|lower }}.yml"
