# $Copyright: Copyright (c) 2024 Veritas Technologies LLC. All rights reserved $

# Verify if the proposed NetBackup client software version is supported.
# Set fact - Netbackup Client Released versions
- name: "NBU-CLIENT-{{ nbu_playbook_type|upper }} ->  Set fact for NBU supported release versions"
  ansible.builtin.set_fact:
    nbu_versions_supported: "{{ nbu_client_rpms_ordered_list.keys() | list }}"

# Set fact - Netbackup Client install/ upgrade supported versions
# Note:- [:-6] is used to get the list of only supported versions among all the NetBackup client software released vesrsions.
- name: "NBU-CLIENT-{{ nbu_playbook_type|upper }} ->  Set fact for NBU supported versions"
  ansible.builtin.set_fact:
    nbu_versions_supported: "{{ nbu_versions_supported[:-6] }}"

# Verify if the proposed NetBackup client software version is supported for install/upgrade
- name: "NBU-CLIENT-{{ nbu_playbook_type|upper }} -> Verify the OS proposed version is compatible for {{ nbu_playbook_type }} of NetBackup Client Version"
  ansible.builtin.fail:
    msg: "ERROR - Incompatible proposed NetBackup client software version {{ nbu_version }} for {{ nbu_playbook_type }}. The supported Netbackup client software versions are {{ nbu_versions_supported }}"
  when:
   - ansible_os_family == "RedHat"
   - nbu_version not in nbu_versions_supported

# EOF
