# $Copyright: Copyright (c) 2024 Veritas Technologies LLC. All rights reserved $

# NetBackup - Packages
nbu_server_rpm_name: VRTSnetbp
nbu_client_rpm_name: VRTSnbcfg
nbu_client_rpm_pddea: VRTSpddea
nbu_client_rpm_vrtsnbcfg: VRTSnbcfg
nbu_client_rpm_pbx: VRTSpbx
nbu_failed_rpms: ""
yum_repolist_output_register: ""

# EEB - Filename
nbu_eeb_prefix: VRTSnbeeb

# OS - Paths
os_path_openv_tmp: /usr/openv/tmp
os_path_nbu_base: /usr
os_path_nbu_install_default: /usr/openv
os_path_nbu_install_etc: /etc/opt/netbackup
os_path_nbu_yum_cache: /var/cache/yum/x86_64/7Server/netbackup
os_path_nbu_log_vxlogcfg: /usr/openv/netbackup/bin/vxlogcfg
bpclntcmd_file: "{{ os_path_nbu_install_default }}/netbackup/bin/bpclntcmd"
nbu_certificates_file_path: /usr/openv/var/tmp      # NBU Installer path where cert mangement dir will be created
os_path_nbu_yum_cache_base: /var
os_path_root_file_system: /

# OS - Files
os_file_nbu_bpkill: "{{ os_path_nbu_install_default }}/netbackup/bin/bp.kill_all"
os_file_nbu_bpps: "{{ os_path_nbu_install_default }}/netbackup/bin/bpps"
os_file_nbu_goodies_netbackup: "{{ os_path_nbu_install_default }}/netbackup/bin/goodies/netbackup"

# EEB Patch
nbu_pack_summary_path: /usr/openv/pack/pack.summary
nbu_eeb_file_base: "{{ item | basename }}"                      # Extract filename from EEB path
nbu_eeb_filename: "{{ item.value.package | basename }}"
nbu_eeb_file_id: "{{ nbu_eeb_file_base.split('_')[1] }}"
nbu_eeb_file_ver: "{{ nbu_eeb_file_base.split('_')[2] }}"
eeb_name: "{{ nbu_eeb_file_base.split(' ')[0] }}"
nbu_eeb_rpm_marker_name: "VRTSnbeeb_{{ nbu_eeb_file_id }}-{{ nbu_eeb_file_ver }}-{{ nbu_version }}.x86_64"

# Local static variable initialization
nbu_client_install_counter: 0
nbu_client_upgrade_counter: 0
nbu_primary_server_ans_found: false

# Certificate management resources
nbu_certificates_file_dir: certinfo                             # newly created directory for keeping cert management files
nbu_CACertificate_File: NBU_Fingerprint                         # name of CACertificate file
nbu_authorization_token_file: NBU_Token                         # name of Authorization token file

# Disk Space variables
os_path_install_space_validation:
  - { path: "{{os_path_nbu_base}}", space_required_MB: 4500 }
  - { path: "{{os_path_nbu_yum_cache_base}}", space_required_MB: 700 }
os_path_upgrade_space_validation:
  - { path: "{{os_path_nbu_base}}", space_required_MB: 2800 }
  - { path: "{{os_path_nbu_yum_cache_base}}", space_required_MB: 700 }

# Ordered list of NetBackup Packages per supported version
nbu_client_rpms_ordered_list:
  "10.4.0.0": {"VRTSnbpck": null, "VRTSpbx": "1.19.4.0", "VRTSnbclt": null, "VRTSnbclibs": null, "VRTSnbjre": null, "VRTSnbjava": null, "VRTSpddea": "20.4.0.0", "VRTSnbcfg": null}
  "10.3.0.1": {"VRTSnbpck": null, "VRTSpbx": "1.18.8.0", "VRTSnbclt": null, "VRTSnbclibs": null, "VRTSnbjre": null, "VRTSnbjava": null, "VRTSpddea": "19.0.1.0", "VRTSnbcfg": null}
  "10.3.0.0": {"VRTSnbpck": null, "VRTSpbx": "1.18.8.0", "VRTSnbclt": null, "VRTSnbclibs": null, "VRTSnbjre": null, "VRTSnbjava": null, "VRTSpddea": "19.0.0.0", "VRTSnbcfg": null}
  "10.2.0.1": {"VRTSnbpck": null, "VRTSpbx": "1.17.62.5", "VRTSnbclt": null, "VRTSnbclibs": null, "VRTSnbjre": null, "VRTSnbjava": null, "VRTSpddea": "18.0.1.0", "VRTSnbcfg": null}
  "10.2.0.0": {"VRTSnbpck": null, "VRTSpbx": "1.17.62.3", "VRTSnbclt": null, "VRTSnbclibs": null, "VRTSnbjre": null, "VRTSnbjava": null, "VRTSpddea": "18.0.0.0", "VRTSnbcfg": null}
  "10.1.1.0": {"VRTSnbpck": null, "VRTSpbx": "1.17.46.1", "VRTSnbclt": null, "VRTSnbclibs": null, "VRTSnbjre": null, "VRTSnbjava": null, "VRTSpddea": "17.1.0.0", "VRTSnbcfg": null}
  "10.1.0.0": {"VRTSnbpck": null, "VRTSpbx": "1.17.43.0", "VRTSnbclt": null, "VRTSnbclibs": null, "VRTSnbjre": null, "VRTSnbjava": null, "VRTSpddea": "17.0.0.0", "VRTSnbcfg": null}
  "10.0.0.1": {"VRTSnbpck": null, "VRTSpbx": "1.17.14.0", "VRTSnbclt": null, "VRTSnbjre": null, "VRTSnbjava": null, "VRTSpddea": "16.0.1.0", "VRTSnbcfg": null}
  "10.0.0.0": {"VRTSnbpck": null, "VRTSpbx": "1.17.11.0", "VRTSnbclt": null, "VRTSnbjre": null, "VRTSnbjava": null, "VRTSpddea": "16.0.0.0", "VRTSnbcfg": null}
  "9.1.0.1": {"VRTSnbpck": null, "VRTSpbx": "1.15.3.0", "VRTSnbclt": null, "VRTSnbjre": null, "VRTSnbjava": null, "VRTSpddea": "15.0.2.0", "VRTSnbcfg": null}
  "9.1.0.0": {"VRTSnbpck": null, "VRTSpbx": "1.15.3.0", "VRTSnbclt": null, "VRTSnbjre": null, "VRTSnbjava": null, "VRTSpddea": "15.0.0.0", "VRTSnbcfg": null}
  "9.0.0.0": {"VRTSnbpck": null, "VRTSpbx": "1.13.5.0", "VRTSnbclt": null, "VRTSnbjre": null, "VRTSnbjava": null, "VRTSpddea": "14.0.0.0", "VRTSnbcfg": null}
  "8.3.0.2": {"VRTSnbpck": null, "VRTSpbx": "1.12.27.0", "VRTSnbclt": null, "VRTSnbjre": null, "VRTSnbjava": null, "VRTSpddea": "13.0.2.0", "VRTSnbcfg": null}
  "8.3.0.1": {"VRTSnbpck": null, "VRTSpbx": "1.12.27.0", "VRTSnbclt": null, "VRTSnbjre": null, "VRTSnbjava": null, "VRTSpddea": "13.0.1.0", "VRTSnbcfg": null}
  "8.3.0.0": {"VRTSnbpck": null, "VRTSpbx": "1.12.22.0", "VRTSnbclt": null, "VRTSnbjre": null, "VRTSnbjava": null, "VRTSpddea": "13.0.0.0", "VRTSnbcfg": null}

# EOF
