# $Copyright: Copyright (c) 2024 Veritas Technologies LLC. All rights reserved $

# Verify whether the machine has the NetBackup software installed
- name: "NBU-VERSION-CHECK -> Verify if NetBackup Software is currently installed"
  ansible.builtin.stat:
    path: "{{ os_path_nbu_install }}/netbackup/bin/version"
  register: netbackup_version_file_register
  failed_when: false
  changed_when: false 

- name: "NBU-VERSION-CHECK -> Verify what version of the NetBackup software is currently installed"
  ansible.builtin.shell:
    cmd: "cat {{ os_path_nbu_install }}/netbackup/bin/version | awk -F ' ' '{print $2}'"
  changed_when: false
  failed_when: false
  register: nbu_version_register

- name: "NBU-VERSION-CHECK -> Verify installed NetBackup software version"
  block:
    - name: "NBU-VERSION-CHECK -> Set NetBackup Version from version.txt"
      ansible.builtin.set_fact:
        nbu_current_installed_version: "{{ nbu_version_register.stdout }}"

    - name: "NBU-VERSION-CHECK -> Formatting NetBackup Version into x.x.x.x format"
      ansible.builtin.set_fact:
        nbu_current_installed_version: "{{ nbu_current_installed_version + '.' + '0' * (1 - (nbu_current_installed_version | regex_replace('.', '') | length) ) }}"
      when: nbu_current_installed_version | regex_findall('\.') | length < 3
      loop: "{{ range(3) | list }}"
    
    - name: Ansible::Log.info
      ansible.builtin.debug:
        msg: "The NetBackup version ({{ nbu_current_installed_version }}) is currently installed."
  when:
    - ( nbu_version_register.stdout != "" )

# EOF
