# $Copyright: Copyright (c) 2024 Veritas Technologies LLC. All rights reserved $

#############################################
#### NetBackup Install - Server ("RHEL") ####
#############################################

# Initializing pre-install phase
- name: "NBU-{{ nbu_role|upper }}-{{ nbu_playbook_type|upper }} -> Set fact for install-phase"
  set_fact:
   install_phase : "PRE"

# Import required tasks - Base Install
- name: "NBU-{{ nbu_role|upper }}-{{ nbu_playbook_type|upper }} -> Load required pre-install tasks for NetBackup {{ nbu_role }} {{ nbu_playbook_type }}"
  ansible.builtin.include_tasks: t01_default_settings.yml

# Import required tasks - Base Install
- name: "NBU-{{ nbu_role|upper }}-{{ nbu_playbook_type|upper }} -> Load required tasks for NetBackup {{ nbu_role }} {{ nbu_playbook_type }} "
  ansible.builtin.include_tasks: t02_base_install.yml                      # NetBackup install and Upgrade Base Server Software
  when:
    - ( nbu_install_status == "upgrade" or nbu_install_status == "install")

# EOF