# $Copyright: Copyright (c) 2024 Veritas Technologies LLC. All rights reserved $

#############################################
#### NetBackup Remove - Client ("RHEL") ####
#############################################
# Import required tasks - Base Remove
- name: "NBU-CLIENT-{{ nbu_playbook_type|upper }} -> Verify whether the NetBackup Client is installed and is the version supported for removal by this Playbook"
  ansible.builtin.include_tasks: t01_pre_remove_check.yml

- name: "NBU-CLIENT-{{ nbu_playbook_type|upper }} -> Remove the NetBackup Client"
  ansible.builtin.include_tasks: t03_base_remove.yml

# EOF