#$Copyright: Copyright (c) 2024 Veritas Technologies LLC. All rights reserved. $

#####################################################################
#### nbu-client-remove -> tasks -> t01_pre_remove_check.yml ####
#####################################################################

# These tasks will verify the workflow is being executed on a current NetBackup client
# Define the playbook removal time as variable
- name: "NBU-CLIENT-{{ nbu_playbook_type|upper }} -> Start NetBackup Removal pre-checks"
  ansible.builtin.set_fact:
    status: "started"
    install_time: "{{ lookup('pipe','date +%Y%m%d%H%M%S') }}"

# Verify whether the NetBackup Server software installed
# Do not continue if NetBackup Primary or Media Server is installed
- name: "NBU-CLIENT-{{ nbu_playbook_type|upper }} -> Verify whether NetBackup server software is currently installed"
  ansible.builtin.include_role:
    name: 'generic/server_check'

- name: "NBU-CLIENT-{{ nbu_playbook_type|upper }} -> Set fact for NetBackup RPMs list to validate their existence"
  ansible.builtin.set_fact:
    nbu_client_rpms_version_ordered: "{{ nbu_client_rpms_version_ordered | default('', true) }}{{ item.key }}-{{ item.value | default(nbu_version, true) }}|"
  no_log: true
  with_items:
    - "{{ nbu_client_rpms_ordered_list[nbu_version] | dict2items }}"

- name: "NBU-CLIENT-{{ nbu_playbook_type|upper }} -> Remove the trailing empty item from RPM list"
  ansible.builtin.set_fact:
    nbu_client_rpms_version_ordered: "{{ nbu_client_rpms_version_ordered[:-1] }}"

# Third verification to make certain that the machine is not a NetBackuup Primary or Media Server
# Fail if bptm or version files exist - Indicates that the machine is a NetBackuup Primary or Media Server
- name: "NBU-CLIENT-{{ nbu_playbook_type|upper }} -> Verify whether NetBackup client software is currently installed"
  ansible.builtin.shell: ( rpm -qa | egrep "{{nbu_client_rpms_version_ordered}}" )
  register: nbu_client_rpm_check_register
  failed_when: false
  no_log: true

# If None of the NetBackup 10.1.1 Client RPMs are installed, exit with the message saying that the NetBackup Client RPMs supported by this Playbook are not installed
- name: "NBU-CLIENT-{{ nbu_playbook_type|upper }} -> Ansible::Log.info"
  fail:
    msg: "NetBackup Client {{nbu_version}} is not installed on this machine, hence cannot be removed"
  when:  
    - ( nbu_client_rpm_check_register.rc == 1 )

- name: Ansible::Log.info
  ansible.builtin.debug:
    msg: "The NetBackup client version ({{ nbu_version }}) is currently installed."

# EOF
