# $Copyright: Copyright (c) 2024 Veritas Technologies LLC. All rights reserved $

---
#############################################
#### NetBackup Install - media ("RHEL") ####
#############################################

# Initializing pre-install phase
- name: "NBU-{{ nbu_role|upper }}-{{ nbu_playbook_type|upper }} -> Set fact for install-phase"
  set_fact: 
   install_phase : "PRE"

# Verify the server OS is compatible with NetBackup version.
- ansible.builtin.include_tasks: t01_install_verification.yml

# Import required tasks - Base Install
- name: "NBU-{{ nbu_role|upper }}-{{ nbu_playbook_type|upper }} -> Load required tasks for NetBackup media {{ nbu_playbook_type }} "
  ansible.builtin.include_tasks: t02_base_install.yml                      # NetBackup install and Upgrade Base Server Software
  when:
    - ( nbu_server_status == "upgrade"  or   nbu_server_status == "install")

- name: "NBU-{{ nbu_role|upper }}-{{ nbu_playbook_type|upper }} -> Set fact for install-phase"
  set_fact: 
    install_phase: "POST"

# EOF