# $Copyright: Copyright (c) 2024 Veritas Technologies LLC. All rights reserved $

#####################################################################
#### nbu-server-install -> tasks -> t01_install_status.yml ####
#####################################################################

# These tasks will verify the workflow is being executed on a current NetBackup server
# and will determine whether the NetBackup server software requires installing.
# If the server is not a valid server or the server software doesnt require install, the install
# workflow will exit after this task and no further tasks will be performed.

# Verify whether the NetBackup server has the NetBackup server software installed
# The install will not proceed if the NetBackup server software is not already installed. 
- name: "NBU-{{ nbu_role|upper }}-INSTALL -> Verify whether NetBackup server software ({{ item.key }}) is currently installed"
  ansible.builtin.shell: ( rpm -qa | grep "{{ item.key }}" )
  failed_when: false
  changed_when: false
  register: nbu_server_rpm_check

# Verify new server, install NetBackup
- name: "NBU-{{ nbu_role|upper }}-INSTALL -> Verify whether to install NetBackup server ({{ item.key }}) - Set fact to 'install'"
  ansible.builtin.set_fact:
    nbu_server_install_counter: "{{ nbu_server_install_counter | default(0) | int + 1 }}"
  when:
    - ( nbu_server_rpm_check.rc == 1 )

# Verify what version of the NetBackup server software is currently installed.
# Returned version is used to determine whether the NetBackup server sofware requires upgrading.
- name: "NBU-{{ nbu_role|upper }}-INSTALL -> Verify what version of the NetBackup server software ({{ item.key }}) is currently installed"
  ansible.builtin.shell: ( rpm -qi "{{ item.key }}" | awk '/Version/ { print $3}' )
  ignore_errors: true
  changed_when: false
  register: nbu_server_rpm_version_register
  when:
    - ( nbu_server_rpm_check.rc == 0 )

- name: "NBU-{{ nbu_role|upper }}-INSTALL -> Setting the eventual install status"
  ansible.builtin.set_fact:
    nbu_server_status: install
  when:  ( nbu_server_install_counter |int > 0 )

- name: "NBU-{{ nbu_role|upper }}-INSTALL -> Setting the eventual install status"
  ansible.builtin.set_fact:
    nbu_server_status: none
  when: 
    - ( nbu_server_install_counter |int == 0 )
    - install_phase == "PRE"

- name: "NBU-{{ nbu_role|upper }}-INSTALL -> Get the [{{ item.key }}] rpm version from proposed version list"
  ansible.builtin.set_fact:
      rpm_proposed_version: "{{ rpm_data.value }}"
  with_items: "{{ nbu_pkgs_ordered_list[nbu_role][nbu_version] | dict2items }}"
  loop_control:
    loop_var: rpm_data
  when: rpm_data.key == item.key

- name: Ansible::Log.info
  fail:
    msg:  "This machine has a different version {{ nbu_server_rpm_version_register.stdout }} of NetBackup Server installed, therefore exit immediately."
  when:
    - ( nbu_server_rpm_check.rc == 0 )
    - install_phase == "PRE"
    - ( nbu_server_rpm_version_register.stdout is version_compare(rpm_proposed_version,'>') or nbu_server_rpm_version_register.stdout is version_compare(rpm_proposed_version,'<') )

# EOF
