# $Copyright: Copyright (c) 2024 Veritas Technologies LLC. All rights reserved $

#####################################################
#### NetBackup Cert Management - Client ("RHEL") ####
#####################################################

# Verify Netbackup Client is installed on Machine.
- name: "NBU-CLIENT-CERT-MANAGEMENT -> Load required tasks for NetBackup client Certificate management "
  ansible.builtin.include_tasks: t01_get_certificate.yml
  when: nbu_cert_management == true 

- name: Ansible::Log.info
  ansible.builtin.debug:
    msg: "Skip fetching certificate as the FTO (nbu_cert_management) is turned off."
  when: nbu_cert_management == false  