# $Copyright: Copyright (c) 2024 Veritas Technologies LLC. All rights reserved $

########################################################################################################
#### NBU-ECA-WINCERTSTORE-CERTIFICATE-DEPLOYMENT -> tasks -> t02_win32nt_eca_wincertstore_certificate.yml ####
########################################################################################################

# Define the Certification start time as variable
- name: "NBU-ECA-WINCERTSTORE-CERTIFICATE-DEPLOYMENT -> Netbackup External Certificate deployment started"
  ansible.builtin.set_fact:
    status: "started"
    install_time: "{{ lookup('pipe','date +%Y%m%d%H%M%S') }}"

- name: "NBU-ECA-WINCERTSTORE-CERTIFICATE-DEPLOYMENT-> Set fact for each dictionary item of [ nbu_eca_certdetails ]."
  set_fact:
    nbu_eca_cert_location: "{{ nbu_eca_certdetails.windows_cert_store.nbu_eca_cert_location }}"
    nbu_eca_crl_check_level: "{{ nbu_eca_certdetails.eca_crl.nbu_eca_crl_check_level if nbu_eca_certdetails.eca_crl.nbu_eca_crl_check_level else 'DISABLED' }}"
    nbu_eca_crl_path: "{{ nbu_eca_certdetails.eca_crl.nbu_eca_crl_path }}"

- name: Ansible::Log.info
  fail:
    msg: "The given Primary server is configured to work with windows cert store certificate deployment. You must specify ECA_CERT_PATH to proceed with certificate deployment."
  when: 
    - nbu_eca_cert_location is defined  
    - nbu_eca_cert_location | length == 0 

- name: "NBU-ECA-WINCERTSTORE-CERTIFICATE-DEPLOYMENT -> Verify Windows Certificate file location existence status"
  win_stat:
    path: "{{ item }}"
  register: eca_win_cert_store_path_register  
  loop:
    - "{{ nbu_eca_cert_location }}" 
    - "{{ nbu_eca_crl_path }}" 
  failed_when: false
  changed_when: false  

- name: "NBU-ECA-WINCERTSTORE-CERTIFICATE-DEPLOYMENT-> Should a CRL be honored for the external certificate?"
  fail:
    msg: "nbu_eca_crl_check_level:'{{ nbu_eca_crl_check_level }}' is not a valid option. Must be ( 'USE_CDP', 'USE_PATH', 'DISABLED' )."
  when: 
    - ( nbu_eca_crl_check_level | string )  not in ["USE_CDP", "USE_PATH", "DISABLED"] 

- name: "NBU-ECA-WINCERTSTORE-CERTIFICATE-DEPLOYMENT -> Fail if CRL path does not satify given requirements"
  fail:
    msg: 
      - "Either of the given condition is not met for given CRL location path [nbu_eca_crl_path:'{{ nbu_eca_crl_path }}']"
      - "1) CRL location path value is required." 
      - "2) Not a valid directory"
      - "3) CRL location path does not exist."
  when: 
    - nbu_eca_crl_check_level == "USE_PATH"
    - nbu_eca_crl_path is defined
    - ( eca_win_cert_store_path_register.results[1].stat.exists and not eca_win_cert_store_path_register.results[1].stat.isdir ) or ( not eca_win_cert_store_path_register.results[1].stat.exists and nbu_eca_crl_path | length > 0 ) or nbu_eca_crl_path | length == 0

- name: "NBU-ECA-WINCERTSTORE-CERTIFICATE-DEPLOYMENT -> Update registry with required external certificate parameters on target host"
  win_regedit:
    path: "{{ nbu_registry_path }}\\CurrentVersion\\Config" 
    name: "{{ item.name }}"
    data: "{{ item.data }}"
    type: "{{ item.type }}"
  loop:
    - { name: 'ECA_CERT_PATH', data: '{{ nbu_eca_cert_location }}', type: 'string' }
    - { name: 'ECA_CRL_CHECK_LEVEL', data: '{{ nbu_eca_crl_check_level }}', type: 'string' }
  failed_when: false  

- name: "NBU-ECA-WINCERTSTORE-CERTIFICATE-DEPLOYMENT -> Update registry with CRL Path depending on ECA_CRL_CHECK_LEVEL"
  win_regedit:
    path: "{{ nbu_registry_path }}\\CurrentVersion\\Config"
    name: 'ECA_CRL_PATH'
    data: '{{ nbu_eca_crl_path }}'
    type: 'string'
  when:
    - nbu_eca_crl_check_level == "USE_PATH"
    - nbu_eca_crl_path | length > 0
  failed_when: false  

- name: "NBU-ECA-WINCERTSTORE-CERTIFICATE-DEPLOYMENT -> Run -precheck to ensure no issues with Certificates configured"
  win_command: nbcertcmd -enrollCertificate -precheck 
  args:
    chdir: "{{ os_path_nbu_install }}\\netbackup\\bin"
  changed_when: false
  register: nbu_eca_precheck_register
  failed_when: false
  no_log: true

- name: "NBU-ECA-WINCERTSTORE-CERTIFICATE-DEPLOYMENT -> Force a failure when precheck gives an error" 
  block:
    - name: "NBU-ECA-WINCERTSTORE-CERTIFICATE-DEPLOYMENT -> Remove the external certificate details with respect to primary server: {{ nbu_primary_server_ans }}"
      win_command: nbcertcmd -removeEnrollment 
      args:
        chdir: "{{ os_path_nbu_install }}\\netbackup\\bin"
      changed_when: false
      register: nbu_remove_enrollment_register
      failed_when: false
      no_log: true

    - name: "NBU-ECA-WINCERTSTORE-CERTIFICATE-DEPLOYMENT - Update registry with updated external certificate details after removal "
      win_regedit:
        path: "{{ nbu_registry_path }}\\CurrentVersion\\Config"
        name: "{{ item.name }}"
        data: "{{ item.data }}"
        state: absent
      loop:
        - { name: 'ECA_CERT_PATH', data: '{{ nbu_eca_cert_location }}' }
        - { name: 'ECA_CRL_CHECK_LEVEL', data: '{{ nbu_eca_crl_check_level }}' }  
        - { name: 'ECA_CRL_PATH', data: '{{ nbu_eca_crl_path }}' } 

    - name: "NBU-ECA-WINCERTSTORE-CERTIFICATE-DEPLOYMENT -> Force a failure when precheck gives an error" 
      fail:
        msg: "{{ nbu_eca_precheck_register.stderr_lines }}{{ nbu_eca_precheck_register.stdout }}"
  when:
    - ( nbu_eca_precheck_register.rc != 0 )

- name: "NBU-ECA-WINCERTSTORE-CERTIFICATE-DEPLOYMENT -> Enroll an external certificate with the primary server domain"
  win_command: nbcertcmd -enrollCertificate
  args:
    chdir: "{{ os_path_nbu_install }}\\netbackup\\bin"
  changed_when: false
  register: nbu_enroll_certificate_register
  failed_when: false
  no_log: true

- name: "NBU-ECA-WINCERTSTORE-CERTIFICATE-DEPLOYMENT -> Display Enroll certificate Output" 
  debug:
    msg: "{{ nbu_enroll_certificate_register.stdout }}"
  when: 
    - ( nbu_enroll_certificate_register.rc == 0 )

- name: "NBU-ECA-FILEBASED-CERTIFICATE-DEPLOYMENT -> Remove enrollment when ECA Certificate enrollment fails"
  block:
    - name: "NBU-ECA-WINCERTSTORE-CERTIFICATE-DEPLOYMENT -> Remove enrollment when ECA certificate enrollment fails"
      win_command: nbcertcmd -removeEnrollment 
      args:
        chdir: "{{ os_path_nbu_install }}\\netbackup\\bin"
      changed_when: false
      register: nbu_remove_enrollment_register
      failed_when: false
      no_log: true

    - name: "NBU-ECA-WINCERTSTORE-CERTIFICATE-DEPLOYMENT - Remove the external certificate details with respect to primary server: {{ nbu_primary_server_ans }}"
      win_regedit:
        path: "{{ nbu_registry_path }}\\CurrentVersion\\Config"
        name: "{{ item.name }}"
        data: "{{ item.data }}"
        state: absent
      loop:
        - { name: 'ECA_CERT_PATH', data: '{{ nbu_eca_cert_location }}' }
        - { name: 'ECA_CRL_CHECK_LEVEL', data: '{{ nbu_eca_crl_check_level }}' }  
        - { name: 'ECA_CRL_PATH', data: '{{ nbu_eca_crl_path }}' }

    - name: "NBU-ECA-WINCERTSTORE-CERTIFICATE-DEPLOYMENT -> Force a failure when precheck gives an error" 
      fail:
        msg: "{{ nbu_eca_precheck_register.stderr_lines }}{{ nbu_eca_precheck_register.stdout }}"
  when:
    - ( nbu_enroll_certificate_register.rc != 0 )
