# $Copyright: Copyright (c) 2025 Veritas Technologies LLC. All rights reserved $

#####################################################
#### Stage Packages Locally - ("Linux/Windows") ####
#####################################################

- name: "NBU-STAGE-PACKAGES -> Setup the netbackup repo and stage packages"
  ansible.builtin.include_tasks: "{{ ansible_system|lower }}.yml"

# EOF