# $Copyright: Copyright (c) 2026 Cohesity, Inc. All rights reserved $

- name: "NBU-INITIALIZE-{{ nbu_playbook_type|upper }} -> Check Python interpreter version"
  ansible.builtin.fail:
    msg: "Host {{ ansible_fqdn }} is using Python {{ ansible_python_version }} ({{ ansible_python.executable }}), which does not meet the minimum requirement of 3.9. If higher python version installed, make sure to set 'ansible_python_interpreter' to that path using extra vars."
  when: ansible_python_version is version('3.9', '<')

- name: "NBU-INITIALIZE-{{ nbu_playbook_type|upper }} -> Initialize platform specific CLIs"
  ansible.builtin.include_tasks: "initialize_clis.yml"

#EOF