# $Copyright: Copyright (c) 2026 Cohesity, Inc. All rights reserved $

###########################################################
#### nbu-eeb-mgmt -> tasks -> main.yml ####
###########################################################
- name: "NBU-EEB-INSTALL -> Configure NetBackup Repository"
  ansible.builtin.include_tasks: t01_nbu_repo_management.yml
  when:
    - nbu_playbook_type is defined
    - nbu_playbook_type == 'eeb'

# Install NetBackup EEBS for the specific NetBackup Version
- name: "NBU-EEB-INSTALL -> NBU services start and stop block"
  block:
  - name: "NBU-EEB-INSTALL -> Stopping NetBackup daemons"
    ansible.builtin.include_role:
      name: 'netbackup/{{ nbap_ansible_system }}/nbu-stop-services'
    when: nbap_invocation_method | default("ansible") == "ansible"

  - name: "NBU-EEB-INSTALL -> Include tasks for NetBackup EEB installation" 
    ansible.builtin.include_tasks: t01_base_patch_eeb.yml
    loop: "{{ nbu_eeb_ordered[nbu_role][nbu_version] }}"
    when:
    - nbu_eeb_ordered[nbu_role][nbu_version] is defined

  always:
  # Check if NetBackup daemons are down
  - name: "NBU-EEB-INSTALL -> Check if NetBackup Daemons Are Down"
    ansible.builtin.shell: ( {{ os_file_nbu_bpps }} -a | egrep 'bpcd|vnetd' | grep standalone | wc -l | grep -q '2' )
    register: bpps_2
    failed_when: false
    changed_when: false
    when: nbap_invocation_method == "ansible"

  # Start the NetBackup daemons, if they are down
  - name: "NBU-EEB-INSTALL -> Start the NetBackup Daemons"
    ansible.builtin.shell: ( {{ os_file_nbu_goodies_netbackup }} )
    failed_when: false
    when:
      - nbap_invocation_method == "ansible"
      - bpps_2.rc|int != 0

# EOF
