## $Copyright: Copyright (c) 2025 Veritas Technologies LLC. All rights reserved $
- name: "NBU-VERSION-CHECK -> Gather facts for version status"
  ansible.builtin.include_role:
    name: 'helper/nbu_version_installed'

# Execute the role which detect the partial install status
- name: "NBU-ROLE-STATUS -> Execute the partial install status role"
  ansible.builtin.include_role:
    name: 'helper/detect_partial_install'

- name: "NBU-ROLE-STATUS -> Load required tasks for NetBackup Role Check"
  ansible.builtin.include_tasks: "{{ ansible_system|lower }}.yml"
  when:
   - nbu_detected_role == "NOT_FOUND"
   - ( not nbap_partial_install_detected )

- name: "NBU-ROLE-STATUS -> Load required tasks for NetBackup Role Check for partial installation"
  block:
    - name: "NBU-ROLE-STATUS -> Set NBU_Role to ( nbu_detected_role ) if nbu_role is undefined" 
      ansible.builtin.set_fact:
        nbu_role: "{{ nbap_partial_role_detected if nbu_role is not defined else nbu_role }}"
        nbu_detected_role: "{{ nbap_partial_role_detected }}"
  when:
    - nbap_partial_role_detected is defined
    - ( nbap_partial_install_detected ) 





