# $Copyright: Copyright (c) 2026 Cohesity, Inc. All rights reserved $

- name: "NBU-INITIALIZE -> Get installation path from existing registry variable"
  win_reg_stat:
    path: "{{ nbu_registry_path }}\\CurrentVersion"
    name: "INSTALLDIR"
  register: nbu_install_path_result
  failed_when: false

- name: "NBU-INITIALIZE -> Warning: Custom installation path not allowed during upgrade"
  debug:
    msg: "WARNING: As upgrade is being performed, custom path isn't allowed. Hence continuing with installed path ( {{nbu_install_path_result.value}} )."
  when:
    - nbu_playbook_type is defined
    - nbu_playbook_type == "upgrade"
    - nbu_install_path_result.exists
    - nbu_install_path_result.value is defined
    - nbu_install_path_result.value != ""
    - os_path_nbu_install is defined
    - (nbu_install_path_result.value ) != (os_path_nbu_install )

- name: "NBU-INITIALIZE -> Set installation path from registry"
  ansible.builtin.set_fact:
    os_path_nbu_install: "{{ nbu_install_path_result.value | regex_replace('\\\\$', '') }}"
    nbu_path_nbcertcmd: "{{ nbu_install_path_result.value | regex_replace('\\\\$', '') }}\\NetBackup\\bin\\nbcertcmd.exe"
    os_file_nbu_nbserviceusercmd: "{{ nbu_install_path_result.value | regex_replace('\\\\$', '') }}\\NetBackup\\bin\\goodies\\nbserviceusercmd.exe"
    nbu_bin_path: "{{ nbu_install_path_result.value | regex_replace('\\\\$', '') }}\\NetBackup\\bin"
    nbu_directory_list_to_be_removed:
      - "{{ nbu_install_path_result.value | regex_replace('\\\\$', '') }}\\Help"
      - "{{ nbu_install_path_result.value | regex_replace('\\\\$', '') }}\\msg"
      - "{{ nbu_install_path_result.value | regex_replace('\\\\$', '') }}\\NetBackup"
      - "{{ nbu_install_path_result.value | regex_replace('\\\\$', '') }}\\Patch"
      - "{{ nbu_install_path_result.value | regex_replace('\\\\$', '') }}\\pdde"
      - "{{ nbu_install_path_result.value | regex_replace('\\\\$', '') }}\\Security"
  when: 
    - nbu_install_path_result.exists
    - nbu_install_path_result.value is defined
    - nbu_install_path_result.value != ""


#EOF