# $Copyright: Copyright (c) 2025 Veritas Technologies LLC. All rights reserved $

- name: "NBU-{{ nbu_role|upper }}-{{ nbu_playbook_type|upper }} -> Execute post install steps"
  block: # ( nbu_role == "primary" )
  - name: "NBU-{{ nbu_role|upper }}-{{ nbu_playbook_type|upper }} -> Stop mqbroker service"
    ansible.builtin.shell: ( ./nbmqbroker -stop )
    args:
      chdir: "{{ os_file_nbu_mqbroker }}/bin"

  - name: "NBU-{{ nbu_role|upper }}-{{ nbu_playbook_type|upper }} -> Execute configureMQ"
    ansible.builtin.shell:  ( ./configureMQ -defaultPorts )
    args:
      chdir: "{{ os_file_nbu_mqbroker }}/bin/install"
    environment:
      PAR_GLOBAL_TMP: '{{ os_path_openv_tmp }}'

  - name: "NBU-{{ nbu_role|upper }}-{{ nbu_playbook_type|upper }} -> Start mqbroker service"
    ansible.builtin.shell: ( ./nbmqbroker -start )
    args:
      chdir: "{{ os_file_nbu_mqbroker }}/bin"

  when:
    - ( nbu_role == "primary" )

# EOF